/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import modelUrl from "./bunny.gltf";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(modelUrl);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.bunny.geometry}
        // material={materials["Default OBJ"]}
        castShadow
        receiveShadow
      />
      <meshStandardMaterial
        attach="material"
        color="black"
        roughness={0}
        metalness={1}
      />
    </group>
  );
}

useGLTF.preload(modelUrl);
