/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import modelUrl from "./suzanne.gltf";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(modelUrl);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Suzanne.geometry}
        material={materials["default"]}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload(modelUrl);
